image:
  name: maven:3.8-openjdk-17

stages:
  - build
  - test
  - analyze
  - deploy

maven-build:
  stage: build
  environment: staging
  script:
    - "mvn -DskipTests clean compile"
  tags:
    - docker

maven-test:
  stage: test
  environment: staging
  script:
    - mvn verify
  artifacts:
    when: always
    expire_in: 30 days
    reports:
      junit:
        - "**/surefire-reports/*.xml"
  tags:
    - docker

maven-deploy:
  stage: deploy
  environment: staging
  script:
    - "mvn deploy -DskipTests -DperformRelease"
  rules:
    - if: $CI_COMMIT_BRANCH == "v5-main"
    - if: $CI_COMMIT_BRANCH == "v5-dev"
    - if: $CI_COMMIT_BRANCH =~ /^v5-ft-.*-deploy$/
    - if: $CI_COMMIT_BRANCH =~ /^v5-hf-.*$/
  tags:
    - docker

sonar-analyze:
  stage: analyze
  environment: staging
  script:
    - mvn clean verify sonar:sonar
      -DskipTests
      -Dsonar.host.url="https://sonar.tools.kobalt.fr"
  tags:
    - docker
