stages:
  - prepare
  - build
  - test
  - analyze
  - deploy

variables:
  JAVA_HOME: /usr/lib/jvm/java-11-openjdk

maven-prepare:
  stage: prepare
  script:
    - "./ci/config-test.py"
  artifacts:
    paths:
      - gitlab-ci.build.conf

maven-build:
  stage: build
  environment: staging
  script:
    - "mvn -DskipTests clean compile"

maven-test:
  stage: test
  environment: staging
  script:
    - "source gitlab-ci.build.conf"
    - mvn verify
  artifacts:
    when: always
    expire_in: 30 days
    reports:
      junit:
        - "**/surefire-reports/*.xml"

maven-deploy:
  stage: deploy
  environment: staging
  script:
    - "mvn deploy -DskipTests -DperformRelease"
  only:
    - /^master$/
    - /^dev$/
    - /^ft-.*-deploy$/
    - /^rl-.*$/
    - /^hf-.*$/

sonar-analyze:
  stage: analyze
  environment: staging
  script:
    - "source gitlab-ci.build.conf"
    - mvn clean verify sonar:sonar
      -DskipTests
      -Dsonar.host.url="https://sonar.tools.kobalt.fr"
